### ISSUE TITLE
Neo4jStatement should signal when unsupported operations are called

### ISSUE THREAD

**Issue by britter** [neo4j-contrib/neo4j-jdbc#17]
There are a couple of operations in java.sql.Statement which are not supported by Neoj4Statement, for example ```addBatch(String)``` or ```executeBatch()```. This may be obvious for experienced users of Neo4j (I assume that inserting a batch doesn't make sense in Neo4j ?!). 
However, if one is not aware of this behavior, using this methods will cause hard to find bugs. I propose to write a warning to the log or even better throw an UnsupportedOperationException whenever one of the methods which are currently not implemented is called.

**Comment by cmdares** [comment]
In order to improve the writing performance, hope to achieve "addBatch and executeBatch" as quickly as possible.thanks.

**Comment by britter** [comment]
#35 has been merged so this issue can be closed.
