### ISSUE TITLE
Squirrel SQL doesn't show data correctly

### ISSUE THREAD

**Issue by Wichart009** [neo4j-contrib/neo4j-jdbc#186]
I used Squirrel SQL 3.9.1 with Neo4j-JDBC-Driver 3.4.0, still show warning not JDBC 2.1 compliant, but when I query, the result show as attached. Could you please check and solve for me?
![neo4j-jdbc-squirrelsql](https://user-images.githubusercontent.com/12468949/53715063-386fce00-3e83-11e9-885d-94fbd1760d4a.jpg)

**Comment by jexp** [comment]
You probably want to return scalar properties or use the jdbc connection option to flatten graph entities. 

Nodes and rels are returned as maps

**Comment by Wichart009** [comment]
How to config the JDBC, please ? Thanks.

**Comment by jexp** [comment]
http://neo4j-contrib.github.io/neo4j-jdbc/#_flattening

**Comment by jexp** [comment]
@Wichart009 did that help?

**Comment by Wichart009** [comment]
Sorry for late, Yes, many THANKS for your help.
