### ISSUE TITLE
jackson-databind version 2.9.2 in neo4j-jdbc has multiple high-risk vulnerabilities

### ISSUE THREAD

**Issue by nibiwodong** [neo4j-contrib/neo4j-jdbc#219]
Hi,

I noticed that neo4j-jdbc is still use old jackson-databind version 2.9.2:
https://github.com/neo4j-contrib/neo4j-jdbc/blob/3.4/pom.xml
https://github.com/neo4j-contrib/neo4j-jdbc/blob/3.5/pom.xml
https://github.com/neo4j-contrib/neo4j-jdbc/blob/4.0/pom.xml

There are multiple high-risk vulnerabilities at version jackson-databind 2.9.2.
![image](https://user-images.githubusercontent.com/17465789/76931845-850a3800-6924-11ea-9cdb-0fe39a8fa40e.png)

I am not sure Jackson-databind vuls can be introduced into neo4j-jdbc, but this is still a risk. 

Please Make an assessment of whether an upgrade is required.

Thx a lot!

**Comment by fbiville** [comment]
I think dependabot could be configured for this project if not already.
Dependabot sends PRs for dependency upgrades and explicitly flags security upgrades.
The bot can be configured to auto-merge PRs if the CI passes (and optionally if the review manually approved).

**Comment by jexp** [comment]
@conker84 can you address this?

**Comment by nibiwodong** [comment]
By the way, will neo4j JDBC version 3.4 continue to be maintained?
 Is there a plan to fix version 3.4?

**Comment by fbiville** [comment]
@conker84 has fixed it on the 4.0 branch via 39e38a655ec008dd92e966a87e04faa4332277a1
Not sure if other branches should be patched as well.

**Comment by conker84** [comment]
@fbiville IHMO we can pass older branches

**Comment by fbiville** [comment]
The 3.5 release is currently blocked by https://github.com/neo4j-contrib/neo4j-jdbc/issues/258 FYI.

**Comment by fbiville** [comment]
3.5.2 is finally out: https://github.com/neo4j-contrib/neo4j-jdbc/releases/tag/3.5.2.
The fix is now available to all 4.x and 3.5.x users!
