### ISSUE TITLE
Escaping issue breaks JSON.

### ISSUE THREAD

**Issue by heroicefforts** [neo4j-contrib/neo4j-jdbc#53]
This driver is globally replacing all " with ' :
https://github.com/neo4j-contrib/neo4j-jdbc/blob/2.3/src/main/java/org/neo4j/jdbc/rest/RestQueryExecutor.java#L190

I assume this is because the query is embedded in the JSON post body.  However, I would argue that it should be replacing " with \" or at a minimum not interfering with previously escaped double quotes.  If I try to create a node property with a value that is a JSON string, then the jdbc driver is incorrectly changing it into improperly formatted JSON (even if I've escaped \" the double quotes).  

CREATE (n:Label { json : '{\"key\":\"value\"}' }) --X--> CREATE (n:Label { json : '{\'key\':\'value\'}'})

**Comment by jexp** [comment]
It should probably not do that, but just fail if it not escaped.

`CREATE (n:Label { json : {1} }) `
-> parameter `statement.setParam(1, "{\"key\":\"value\"}")`

In general single quotes for your strings in cypher.
