### ISSUE TITLE
MATCH on label doesn't work

### ISSUE THREAD

**Issue by ericlentz** [neo4j-contrib/neo4j-jdbc#60]
I place this into DbVisualizer:

`MATCH n where (n:Movie) RETURN n`

and it prompts me to provide a value for a parameter. If I provide a value or not, it returns an error. If I run this same query in the neo4j browser (http://localhost:7474/browser), it works fine. I'm trying to find all "Movie" nodes.

**Comment by jexp** [comment]
I think that's a shortcoming of DbVisualizer which interprets our labels as parameters.

Can you try to escape the label with backticks?

aka: 
```
MATCH (n:`Movie`) RETURN n
```

or add some more spaces between colon and label-name?

**Comment by ericlentz** [comment]
Thanks, perfect, the space did it. This works:
`MATCH n where (n: Movie) RETURN n`
